-- Seed data used by local reset and optional linked-remote push include-seed.
--
-- Google Play / demo reviewer login is created via Admin API (npm run supabase:play-review-seed).
-- Optional local manual-test accounts: LOCAL_TESTING_EMAIL / LOCAL_TESTING_PASSWORD in .env,
-- then npm run supabase:local-test-users-seed (runs automatically after supabase:db:reset).
-- Postgres cannot read .env for auth users; seed.sql does not create auth.users rows.
--
-- Set in repo-root .env (optional; defaults are used if unset):
--   SUPABASE_PLAY_REVIEW_PASSWORD=...
--   SUPABASE_PLAY_REVIEW_EMAIL=play-review@wordle-tracker.invalid
--
-- Preferred automated flow:
--   npm run supabase:db:push   (linked remote, includes seed)
--   npm run supabase:db:reset  (local reset, includes seed)
--
-- Manual hosted fallback: create the user in Supabase Dashboard (Authentication) with the
-- email/password you give Google, then if needed:
--   INSERT INTO public.users (id, display_name)
--   SELECT id, 'Google Play Review' FROM auth.users WHERE email = 'your-email@example.com'
--   ON CONFLICT (id) DO NOTHING;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
