/*
  # App-wide configuration and limit RCP updates

  - app_config table: single-row configuration for tournament limits and scoring.
  - get_app_config(): returns the current config for clients.
  - Updates create_tournament_draft and join_tournament_by_code to read limits from app_config.
  - Updates get_tournament_limit_info to derive max_limit from app_config.
*/

-- ============================================================================
-- app_config table
-- ============================================================================

CREATE TABLE IF NOT EXISTS app_config (
  key text PRIMARY KEY,
  max_tournaments_per_user integer NOT NULL DEFAULT 5,
  max_participants_per_tournament integer NOT NULL DEFAULT 15,
  points_guess_1 integer NOT NULL DEFAULT 20,
  points_guess_2 integer NOT NULL DEFAULT 8,
  points_guess_3 integer NOT NULL DEFAULT 6,
  points_guess_4 integer NOT NULL DEFAULT 4,
  points_guess_5 integer NOT NULL DEFAULT 2,
  points_guess_6 integer NOT NULL DEFAULT 1,
  points_missed integer NOT NULL DEFAULT -2,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure a single default row exists
INSERT INTO app_config (key)
VALUES ('default')
ON CONFLICT (key) DO NOTHING;

-- ============================================================================
-- get_app_config RPC
-- ============================================================================

CREATE OR REPLACE FUNCTION get_app_config()
RETURNS TABLE (
  key text,
  max_tournaments_per_user integer,
  max_participants_per_tournament integer,
  points_guess_1 integer,
  points_guess_2 integer,
  points_guess_3 integer,
  points_guess_4 integer,
  points_guess_5 integer,
  points_guess_6 integer,
  points_missed integer,
  updated_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    key,
    max_tournaments_per_user,
    max_participants_per_tournament,
    points_guess_1,
    points_guess_2,
    points_guess_3,
    points_guess_4,
    points_guess_5,
    points_guess_6,
    points_missed,
    updated_at
  FROM app_config
  ORDER BY updated_at DESC
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION get_app_config() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_app_config() TO authenticated;

-- ============================================================================
-- Update create_tournament_draft to use app_config
-- ============================================================================

CREATE OR REPLACE FUNCTION create_tournament_draft(
  p_name text,
  p_start_date date,
  p_end_date date
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_tournament_id uuid;
  v_active_count integer;
  v_max_tournaments integer;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
    RAISE EXCEPTION 'Tournament name is required';
  END IF;

  IF p_end_date < p_start_date THEN
    RAISE EXCEPTION 'Invalid date range';
  END IF;

  -- Read max tournaments per user from app_config (fallback to 4)
  SELECT max_tournaments_per_user
  INTO v_max_tournaments
  FROM app_config
  ORDER BY updated_at DESC
  LIMIT 1;

  IF v_max_tournaments IS NULL THEN
    v_max_tournaments := 4;
  END IF;

  -- Enforce max tournaments per user (draft + active), based on participation.
  SELECT COUNT(*)
  INTO v_active_count
  FROM tournament_participants tp
  JOIN tournaments t ON t.id = tp.tournament_id
  WHERE tp.user_id = v_user_id
    AND t.status IN ('draft', 'active');

  IF v_active_count >= v_max_tournaments THEN
    RAISE EXCEPTION 'You are already in the maximum number of tournaments (%s)', v_max_tournaments;
  END IF;

  -- Create tournament (join_code generated by default)
  INSERT INTO tournaments (name, start_date, end_date, status, created_by)
  VALUES (trim(p_name), p_start_date, p_end_date, 'draft', v_user_id)
  RETURNING id INTO v_tournament_id;

  -- Add creator as a participant
  INSERT INTO tournament_participants (tournament_id, user_id)
  VALUES (v_tournament_id, v_user_id);

  RETURN v_tournament_id;
END;
$$;

REVOKE ALL ON FUNCTION create_tournament_draft(text, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_tournament_draft(text, date, date) TO authenticated;

-- ============================================================================
-- Update join_tournament_by_code to use app_config
-- ============================================================================

CREATE OR REPLACE FUNCTION join_tournament_by_code(p_join_code text)
RETURNS uuid AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_tournament_id uuid;
  v_active_count integer;
  v_participant_count integer;
  v_max_tournaments integer;
  v_max_participants integer;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Load limits from app_config (with sane defaults)
  SELECT
    max_tournaments_per_user,
    max_participants_per_tournament
  INTO
    v_max_tournaments,
    v_max_participants
  FROM app_config
  ORDER BY updated_at DESC
  LIMIT 1;

  IF v_max_tournaments IS NULL THEN
    v_max_tournaments := 4;
  END IF;

  IF v_max_participants IS NULL THEN
    v_max_participants := 15;
  END IF;

  -- Find tournament by join code (case-insensitive), only draft/active
  SELECT id
  INTO v_tournament_id
  FROM tournaments
  WHERE upper(join_code) = upper(p_join_code)
    AND status IN ('draft', 'active')
  LIMIT 1;

  IF v_tournament_id IS NULL THEN
    RAISE EXCEPTION 'Invalid or inactive join code';
  END IF;

  -- Check user is not already a participant
  IF EXISTS (
    SELECT 1
    FROM tournament_participants tp
    WHERE tp.tournament_id = v_tournament_id
      AND tp.user_id = v_user_id
  ) THEN
    RAISE EXCEPTION 'You are already in this tournament';
  END IF;

  -- Enforce max tournaments per user (draft + active)
  SELECT COUNT(*)
  INTO v_active_count
  FROM tournament_participants tp
  JOIN tournaments t ON t.id = tp.tournament_id
  WHERE tp.user_id = v_user_id
    AND t.status IN ('draft', 'active');

  IF v_active_count >= v_max_tournaments THEN
    RAISE EXCEPTION 'You are already in the maximum number of tournaments (%s)', v_max_tournaments;
  END IF;

  -- Enforce max participants per tournament
  SELECT COUNT(*)
  INTO v_participant_count
  FROM tournament_participants tp
  WHERE tp.tournament_id = v_tournament_id;

  IF v_participant_count >= v_max_participants THEN
    RAISE EXCEPTION 'This tournament is full (%s players max)', v_max_participants;
  END IF;

  -- Insert participant row
  INSERT INTO tournament_participants (tournament_id, user_id)
  VALUES (v_tournament_id, v_user_id);

  RETURN v_tournament_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION join_tournament_by_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION join_tournament_by_code(text) TO authenticated;

-- ============================================================================
-- Update get_tournament_limit_info to read limit from app_config
-- ============================================================================

CREATE OR REPLACE FUNCTION get_tournament_limit_info()
RETURNS TABLE (
  current_count integer,
  max_limit integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_max_limit integer;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT max_tournaments_per_user
  INTO v_max_limit
  FROM app_config
  ORDER BY updated_at DESC
  LIMIT 1;

  IF v_max_limit IS NULL THEN
    v_max_limit := 4;
  END IF;

  RETURN QUERY
  SELECT
    COUNT(*)::integer AS current_count,
    v_max_limit::integer AS max_limit
  FROM tournament_participants tp
  JOIN tournaments t ON t.id = tp.tournament_id
  WHERE tp.user_id = v_user_id
    AND t.status IN ('draft', 'active');
END;
$$;

REVOKE ALL ON FUNCTION get_tournament_limit_info() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_tournament_limit_info() TO authenticated;

